# SPDX-FileCopyrightText: 2018 - 2026 DCO App Contributors
# SPDX-License-Identifier: ISC

---
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
