version = 1

[[annotations]]
path = [
    ".node-version",
    ".nvmrc",
    "package.json",
    "package-lock.json",
    "test/__snapshots__/index.test.js.snap",
    "test/fixtures/check_run.rerequested.json",
    "test/fixtures/compare-success.json",
    "test/fixtures/compare.json",
    "test/fixtures/pull_request.opened-success.json",
    "test/fixtures/pull_request.opened.json",
    "test/fixtures/pull_request_review.submitted.json",
    "test/fixtures/pull_request_review_comment.created.json",
    "test/fixtures/merge_group.checks_requested.json",
    "test/fixtures/merge-queue-bot-squash.json",
    "test/fixtures/merge-queue-merge-pr-commits.json",
    "test/fixtures/merge-queue-merge-range.json",
    "test/fixtures/merge-queue-noreply-pr-commits.json",
    "test/fixtures/merge-queue-noreply-squash.json",
    "test/fixtures/merge-queue-pr-commits.json",
    "test/fixtures/merge-queue-rebase-range.json",
    "test/fixtures/merge-queue-squash-fabricated.json",
    "test/fixtures/merge-queue-squash-signed.json",
    "test/fixtures/merge-queue-squash-unsigned.json",
    "test/fixtures/push.not-signed-off.json",
    "test/fixtures/push.signed-off.json",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 - 2026 DCO App Contributors"
SPDX-License-Identifier = "ISC"
