name: Run tests
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    permissions:
      contents: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.4.0

      - name: Setup nodejs
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run tests
        rum: pnpm test
